### PR TITLE
improve the data query speed

### PR DESCRIPTION
**Pull request by ishimwezachee**
In this task, I have improved my query speed in such way; 
# `SELECT COUNT(*) FROM visits where animal_id = 4;`
## Before
data1
## After 
data1after

--------------------------------------------------------------------------------------------------------------------------------------

# `SELECT * FROM visits where vet_id = 2;`
## Before
data2
##
 After 
datachanges

-----------------------------------------------------------------------------------------------------------------------------------------

# `SELECT * FROM owners where email = 'owner_18327@mail.com';`
## Before 
data3

## After 
data3after

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @ishimwezachee, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Your second screenshots show no improvement at all. it seems like the `Execution Time` increased instead. Kindly address the issue and fix it.
scrnli_2_1_2022_9-30-14 AM


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @ishimwezachee, 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
## Required Changes ♻️
  - [ ] I don't know if you have forgotten to push new changes and replace the screenshots Because I don't see any changes. Kindly refer to the previous review and make sure to address the issues so that the `Execution time` for query(`SELECT * FROM visits where vet_id = 2;`) is decreased after the improvement of the performance.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ishimwezachee** [comment]
Hello Eric,  The reason why you've not seen any change is that on the first
pull request, I submitted the wrong screenshot, so after your review, I
have updated my screenshot from my pull requests. so Check on my pull
request message you will see that there is a change on the second query.
Thank you

**Comment by ishimwezachee** [comment]
Hello Eric,  The reason why you've not seen any change is that on the first
pull request, I submitted the wrong screenshot, so after your review, I
have updated my screenshot from my pull requests. so Check on my pull
request message you will see that there is a change on the second query.
Thank you

**Comment by AshakaE** [comment]
### Hi @ishimwezachee   🙋‍♀️, 

# STATUS APPROVED ✔
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
